const fs = require('fs');
const path = require('path');
const readline = require('readline');
const crypto = require('crypto');
const { Pool } = require('pg');

const envPath = path.join(__dirname, '..', '.env');

function question(rl, prompt) {
  return new Promise((resolve) => rl.question(prompt, resolve));
}

function buildEnvContent({ password, jwtSecret }) {
  return `# Local secrets — generated by npm run setup

PORT=3000

DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=${password}
DB_NAME=postgres

JWT_SECRET=${jwtSecret}
`;
}

async function testConnection(config) {
  const pool = new Pool({
    host: config.host,
    port: config.port,
    user: config.user,
    password: config.password,
    database: config.database,
  });
  try {
    await pool.query('SELECT 1');
    return true;
  } finally {
    await pool.end();
  }
}

async function main() {
  console.log(`
VisionTrack — PostgreSQL setup
PostgreSQL service detected on this machine (postgresql-x64-18).

Use the password for the "postgres" user from PostgreSQL installation.
If you forgot it: open pgAdmin 4 → connect to local server → change password for Login/Group Role "postgres".
`);

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  let password = '';
  while (!password.trim()) {
    password = await question(
      rl,
      'Enter PostgreSQL password for user "postgres": ',
    );
    if (!password.trim()) {
      console.log('Password cannot be empty.\n');
    }
  }

  rl.close();

  const jwtSecret = crypto.randomBytes(32).toString('hex');
  const config = {
    host: '127.0.0.1',
    port: 5432,
    user: 'postgres',
    password: password.trim(),
    database: 'postgres',
  };

  process.stdout.write('Testing connection... ');
  try {
    await testConnection(config);
    console.log('OK');
  } catch (err) {
    console.log('FAILED\n');
    console.error(
      'Could not connect. Check that PostgreSQL is running and the password is correct.\n',
    );
    console.error(err.message);
    process.exit(1);
  }

  fs.writeFileSync(envPath, buildEnvContent({ password: config.password, jwtSecret }), {
    encoding: 'utf8',
  });
  console.log(`\nWrote ${envPath}`);
  console.log('Next: node initDb.js   then   npm run dev\n');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
